version: '3.4'

services:
  ucrud.server:
    container_name: ucrud.server
    image: ${DOCKER_REGISTRY-}ucrudserver
    ports:
      - "5555:80"
    build:
      context: .
      dockerfile: uCRUD/Server/Dockerfile
  sqldb:
      container_name: sqldb
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - SA_PASSWORD=2Secure*Password2
        - ACCEPT_EULA=Y
      ports:
        - "1440:1433"  